<a href="https://colab.research.google.com/github/joserodriguezc/linear_algebra/blob/main/Numpy/Linear_Algebra_Numpy_Matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Vectors and Vector Arithmetic**

*Vectors are built from components, which are ordinary numbers. You can think of a vector as a list of numbers, and vector algebra as operations performed on the numbers in the list.*
No Bullshit Guide To Linear Algebra, 2017.



v = (v1; v2; v3)

In [2]:
# create a vector
from numpy import array
# define vector
v = array([10, 22, 343])
print(v)

[ 10  22 343]


Basic Arithmetic

In [4]:
vector1 = array([1,5,7])
vector2 = array([0.2,0.5,3.5])

In [5]:
add = vector1 + vector2
print(add)

[ 1.2  5.5 10.5]


In [7]:
sust = vector1 - vector2
print(sust)

[0.8 4.5 3.5]


In [8]:
mul = vector1 * vector2
print(mul)

[ 0.2  2.5 24.5]


In [9]:
div = vector1 / vector2
print(div)

[ 5. 10.  2.]


Dot Product

c = a . b   
c = c = (a1 * b1 + a2 * b2 + a3 * b3)

In [11]:
dot = vector1.dot(vector2)
print(dot)

27.2
