<a href="https://colab.research.google.com/github/joserodriguezc/linear_algebra/blob/main/Numpy/Linear_Algebra_Numpy_Matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Vectors and Vector Arithmetic**

*Vectors are built from components, which are ordinary numbers. You can think of a vector as a list of numbers, and vector algebra as operations performed on the numbers in the list.*
No Bullshit Guide To Linear Algebra, 2017.



v = (v1; v2; v3)

In [2]:
# create a vector
from numpy import array
# define vector
v = array([10, 22, 343])
print(v)

[ 10  22 343]


Basic Arithmetic

In [4]:
vector1 = array([1,5,7])
vector2 = array([0.2,0.5,3.5])

In [5]:
add = vector1 + vector2
print(add)

[ 1.2  5.5 10.5]


In [7]:
sust = vector1 - vector2
print(sust)

[0.8 4.5 3.5]


In [8]:
mul = vector1 * vector2
print(mul)

[ 0.2  2.5 24.5]


In [9]:
div = vector1 / vector2
print(div)

[ 5. 10.  2.]


Dot Product

c = a . b   
c = c = (a1 * b1 + a2 * b2 + a3 * b3)

In [11]:
dot = vector1.dot(vector2)
print(dot)

27.2


In [13]:
dot == sum(mul)

True

## Vector Norms

* The L1 norm that is calculated as the sum of the absolute values of the vector.
* The L2 norm that is calculated as the square root of the sum of the squared vector values.
* The max norm that is calculated as the maximum vector values.

L1 norm   
||v||1 = |a1| + |a2| + |a3|   
Manhatan Distance

In [14]:
from numpy.linalg import norm
# define vector
a = array([1, 2, 3])
print(a)
# calculate norm
l1 = norm(a, 1)
print(l1)

[1 2 3]
6.0


L2 norm   
||v||2 = sqr(a21 + a22 + a23)  
Euclidean Distance

In [15]:
a = array([1, 2, 3])
print(a)
# calculate norm
l2 = norm(a)
print(l2)

[1 2 3]
3.7416573867739413


In [32]:
a = 1 * 1
b = 2 * 2
c = 3 * 3
s = a + b + c
l2 = np.sqrt(s)
print(l2)

3.7416573867739413


**Matrix**   
A matrix is a two-dimensional array of scalars with one or more columns and one or more rows. i.e a table of numbers   


In [34]:
A = array([[3, 12, 33], [4, 44, 567]])
print(A)

[[  3  12  33]
 [  4  44 567]]


add

In [35]:
# define first matrix
A = array([
[1, 2, 3],
[4, 5, 6]])
print(A)
# define second matrix
B = array([
[1, 2, 3],
[4, 5, 6]])
print(B)
# add matrices
C = A + B
print(C)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[ 2  4  6]
 [ 8 10 12]]


Substraction

In [37]:
# define first matrix
A = array([
[1, 2, 3],
[4, 5, 6]])
print(A)
# define second matrix
B = array([
[0.5, 0.5, 0.5],
[0.5, 0.5, 0.5]])
print(B)
# subtract matrices
C = A - B
print(C)

[[1 2 3]
 [4 5 6]]
[[0.5 0.5 0.5]
 [0.5 0.5 0.5]]
[[0.5 1.5 2.5]
 [3.5 4.5 5.5]]


Hadamard Product

In [38]:
# define first matrix
A = array([
[1, 2, 3],
[4, 5, 6]])
print(A)
# define second matrix
B = array([
[1, 2, 3],
[4, 5, 6]])
print(B)
# multiply matrices
C = A * B
print(C)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[ 1  4  9]
 [16 25 36]]


Division

In [39]:
# define first matrix
A = array([
[1, 2, 3],
[4, 5, 6]])
print(A)
# define second matrix
B = array([
[1, 2, 3],
[4, 5, 6]])
print(B)
# divide matrices
C = A / B
print(C)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1. 1. 1.]
 [1. 1. 1.]]


Dot product

In [41]:
#define first matrix
A = array([
[1, 2],
[3, 4],
[5, 6]])
print(A)
# define second matrix
B = array([
[1, 2],
[3, 4]])
print(B)
# multiply matrices
C = A.dot(B)
print(C)
# multiply matrices with @ operator
D = A @ B
print(D)

[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]]
[[ 7 10]
 [15 22]
 [23 34]]
[[ 7 10]
 [15 22]
 [23 34]]
