<a href="https://colab.research.google.com/github/joserodriguezc/linear_algebra/blob/main/Numpy/Linear_Algebra_Numpy_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Numpy Arrays**   
Arrays are the main data structure used in machine learning. In Python, arrays from the NumPy library, called N-dimensional arrays or the *ndarray*, are used as the primary data structure for representing data


In [8]:
# create array
from numpy import array
# create array
l = [1.43, 2.0, 5.67]
a = array(l)
# display array
print(a)
# display array shape
print(a.shape)
# display array data type
print(a.dtype)

[1.43 2.   5.67]
(3,)
float64


In [7]:
from numpy import empty
a = empty([3,5])
print(a)

[[4.65257065e-310 1.03977794e-312 1.01855798e-312 9.54898106e-313
  1.08221785e-312]
 [1.01855798e-312 1.23075756e-312 1.06099790e-312 1.12465777e-312
  9.76118064e-313]
 [1.20953760e-312 1.01855798e-312 1.18831764e-312 4.44659081e-322
  0.00000000e+000]]


In [9]:
from numpy import zeros
a = zeros([3,3])
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [10]:
from numpy import ones
a = ones([5])
print(a)

[1. 1. 1. 1. 1.]


Vertical Stack

In [18]:
#create array with vstack
from numpy import vstack
# create first array
a1 = array([1,2,3])
print(a1)
# create second array
a2 = array([4,5,6])
print(a2)
# vertical stack
a3 = vstack((a1, a2))
print(a3)
print(a3.shape)

[1 2 3]
[4 5 6]
[[1 2 3]
 [4 5 6]]
(2, 3)


Horizontal Stack

In [15]:
from numpy import hstack
# create first array
a1 = array([1,2,3])
print(a1)
# create second array
a2 = array([4,5,6,7,8])
print(a2)
# create horizontal stack
a3 = hstack((a1, a2))
print(a3)
print(a3.shape)

[1 2 3]
[4 5 6 7 8]
[1 2 3 4 5 6 7 8]
(8,)


One-Dimensional List to Array

In [19]:
# list of data
data = [11, 22, 33, 44, 55]
# array of data
data = array(data)
print(data)
print(type(data))

[11 22 33 44 55]
<class 'numpy.ndarray'>


Two-Dimensional List of Lists to Array

In [20]:
# list of data
data = [[11, 22],
[33, 44],
[55, 66]]
# array of data
data = array(data)
print(data)
print(type(data))

[[11 22]
 [33 44]
 [55 66]]
<class 'numpy.ndarray'>


Broadcasting

In [25]:
# broadcast scalar to one-dimensional array
# define array
a = array([1, 2, 3])
print(a)
# define scalar
b = 2
print(b)
# broadcast
c = a + b
print(c)

[1 2 3]
2
[3 4 5]


In [23]:
# broadcast scalar to two-dimensional array
# define array
A = array([
[1, 2, 3],
[1, 2, 3]])
print(A)
# define scalar
b = 2
print(b)
# broadcast
C = A + b
print(C)


[[1 2 3]
 [1 2 3]]
2
[[3 4 5]
 [3 4 5]]


In [24]:
# broadcast one-dimensional array to two-dimensional array
# define two-dimensional array
A = array([
[1, 2, 3],
[1, 2, 3]])
print(A)
# define one-dimensional array
b = array([1, 2, 3])
print(b)
# broadcast
C = A + b
print(C)

[[1 2 3]
 [1 2 3]]
[1 2 3]
[[2 4 6]
 [2 4 6]]


In [28]:
# broadcasting error
# define two-dimensional array
A = array([
[1, 2, 3],
[1, 2, 3]])
print(A.shape)
# define one-dimensional array
b = array([1,2,3,4])
print(b.shape)
# attempt broadcast
C = A + b
print(C)

(2, 3)
(4,)


ValueError: ignored